/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizmanagementsystem;

import javax.swing.JOptionPane;
import quizmanagementsystem.entities.User;
import utils.Common;

/**
 *
 * @author Hassaan.Siddique
 */
public class Settings extends javax.swing.JPanel {
    private User user = Login.logedInUser;
    /**
     * Creates new form AddQuestion
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        option3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        updateSetting = new javax.swing.JButton();
        newPassword = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(1500, 700));
        setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(1220, 40, 120, 40);
        add(username);
        username.setBounds(200, 40, 380, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(80, 40, 200, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        add(jLabel7);
        jLabel7.setBounds(650, 40, 200, 40);

        settingsPanel.setBackground(new java.awt.Color(102, 102, 102));
        settingsPanel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        settingsPanel.add(jLabel4);
        jLabel4.setBounds(120, 50, 200, 40);

        option3.setEditable(false);
        settingsPanel.add(option3);
        option3.setBounds(350, 50, 380, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("New Password");
        settingsPanel.add(jLabel11);
        jLabel11.setBounds(120, 130, 200, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confirm Password");
        settingsPanel.add(jLabel12);
        jLabel12.setBounds(120, 210, 200, 40);
        settingsPanel.add(name);
        name.setBounds(350, 290, 380, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        settingsPanel.add(jLabel6);
        jLabel6.setBounds(120, 290, 200, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email address");
        settingsPanel.add(jLabel10);
        jLabel10.setBounds(120, 370, 200, 40);
        settingsPanel.add(email);
        email.setBounds(350, 370, 380, 40);

        updateSetting.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateSetting.setText("Update Settings");
        updateSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSettingActionPerformed(evt);
            }
        });
        settingsPanel.add(updateSetting);
        updateSetting.setBounds(570, 460, 170, 50);
        settingsPanel.add(newPassword);
        newPassword.setBounds(350, 130, 380, 40);
        settingsPanel.add(confirmPassword);
        confirmPassword.setBounds(350, 210, 380, 40);

        add(settingsPanel);
        settingsPanel.setBounds(40, 130, 820, 520);
        add(password);
        password.setBounds(760, 40, 380, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(username.getText().equals(user.getUserName()) && password.getText().equals(user.getPassword())){
            username.setEditable(false);
            password.setEditable(false);
            option3.setText(user.getUserName());
            settingsPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Username or Password...!");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSettingActionPerformed
        if(newPassword.getText().equals(confirmPassword.getText())){
            if(isAllFieldsFilled()){
                user.setPassword(newPassword.getText());
                user.setName(name.getText());
                user.setEmail(email.getText());
                System.out.println("user data: "+user.toString());
                user.update();
                Login.logedInUser = user;
                clear();
            } else {
                JOptionPane.showMessageDialog(null, "Please fill all fields to update settings.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "New Password and Confirm password does match each other.");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_updateSettingActionPerformed


    public void clear(){
        settingsPanel.setVisible(false);
        username.setEditable(true);
        password.setEditable(true);
        username.setText("");
        password.setText("");
        name.setText("");
        newPassword.setText("");
        confirmPassword.setText("");
        email.setText("");
        
    }
 
    
    public boolean isAllFieldsFilled(){
        return !Common.isEmptyString(name.getText()) &&
                !Common.isEmptyString(newPassword.getText()) &&
                !Common.isEmptyString(confirmPassword.getText()) &&
                !Common.isEmptyString(email.getText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JTextField option3;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JButton updateSetting;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
